# Generated by Django 5.0.6 on 2025-02-02 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_answer_bn_faq_answer_hi_faq_answer_ka_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='answer_ka',
            new_name='answer_kn',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_ka',
            new_name='question_kn',
        ),
    ]
